// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw93hnJynGsvxRErBNAH1cOGvVVpkvixI',
    appId: '1:171371310460:web:47e75a1786d491001388f9',
    messagingSenderId: '171371310460',
    projectId: 'solomento-records',
    authDomain: 'solomento-records.firebaseapp.com',
    storageBucket: 'solomento-records.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAeL-SEsXtqWea6vQJ6AOtorOfE7tZQ1I',
    appId: '1:171371310460:android:1c023dee0001aa8e1388f9',
    messagingSenderId: '171371310460',
    projectId: 'solomento-records',
    storageBucket: 'solomento-records.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6v6xobgpxUwxh96OR0LBX8Gvgt3oyc4',
    appId: '1:171371310460:ios:76fd0b4c86c3f6cc1388f9',
    messagingSenderId: '171371310460',
    projectId: 'solomento-records',
    storageBucket: 'solomento-records.appspot.com',
    iosBundleId: 'com.example.solomentoRecords',
  );
}
