name: record_repository
description: "Dart package that manages the records."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  equatable: ^2.0.5
  cloud_firestore: ^5.4.4

  # Custom Repository
  user_repository:
    path: ../user_repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
